#!/bin/bash

# This script sets up a new container environment using debootstrap and configures networking for it.
# It creates a new root filesystem in /var/new.root and sets up a network namespace with a virtual Ethernet pair.
# It also configures iptables for NAT and forwarding between the new namespace and the host network.
source env-setup


# Verify running on Linux
if [[ "$(uname -s)" != "Linux" ]]; then
    echo "Error: This script must be run on a Linux system."
    exit 1
fi

echo "Building new root @ ${TARGET}..."

echo "  Checking for debootstrap installation..."
which debootstrap
if [ $? != 0 ]; then
    echo "debootstrap not found. Installing..."
    apt-get -y install debootstrap
fi

# Create a new container and network namespace, using Debian stable as the rootfs
echo "  Create a new container and network namespace, using Debian stable as the rootfs..."
if [ -d ${TARGET} ];
then
    rm -rf ${TARGET} 
fi

mkdir ${TARGET}
debootstrap stable ${TARGET} http://httpredir.debian.org/debian/
if [ $? != 0 ]; then
    echo "Error: debootstrap failed to create the root filesystem."
    exit 1
fi
echo "  Configuring the new root filesystem..."
echo "  Setting up the new root filesystem..."



chroot ${TARGET} /bin/sh -c "mount -t proc none /proc && \
    mount -t sysfs none /sys && \
    mount -t devtmpfs none /dev && \
    mount -t tmpfs none /run && \
    mount -t proc none /proc"


# ip netns allows applications that are namespace unware run in a separate network namespace
ip netns add netns1
unshare --mount --uts --ipc --net=/var/run/netns/netns1 --pid --fork /bin/bash 

# In a separate process, configure the new network namespace
ip link add veth0 type veth peer name veth1
ip link set veth1 netns netns1
ip addr add 172.16.99.1/24 dev veth0
ip link set veth0 up
ip netns exec netns1 ip addr add 172.16.99.100/24 dev veth1
ip netns exec netns1 ip link set lo up
ip netns exec netns1 ip link set veth1 up
ip netns exec netns1 ip route add default via 172.16.99.1

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -P FORWARD DROP
iptables -F FORWARD
iptables -t nat -F
iptables -t nat -A POSTROUTING -s 172.16.99.100/24 -o enp0s3 -j MASQUERADE
iptables -A FORWARD -i enp0s3 -o veth0 -j ACCEPT
iptables -A FORWARD -o enp0s3 -i veth0 -j ACCEPT


